//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DwarvenRealms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public int mapCenterX {
            get {
                return ((int)(this["mapCenterX"]));
            }
            set {
                this["mapCenterX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public int mapCenterY {
            get {
                return ((int)(this["mapCenterY"]));
            }
            set {
                this["mapCenterY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int tilesPerRegionTile {
            get {
                return ((int)(this["tilesPerRegionTile"]));
            }
            set {
                this["tilesPerRegionTile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:/DwarfFortress/df_34_11_win/world_graphic-el-region1-250-16014.bmp")]
        public string elevationMapPath {
            get {
                return ((string)(this["elevationMapPath"]));
            }
            set {
                this["elevationMapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:/DwarfFortress/df_34_11_win/world_graphic-elw-region1-250-16014.bmp")]
        public string elevationWaterMapPath {
            get {
                return ((string)(this["elevationWaterMapPath"]));
            }
            set {
                this["elevationWaterMapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hydrosphereMapPath {
            get {
                return ((string)(this["hydrosphereMapPath"]));
            }
            set {
                this["hydrosphereMapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Users/Japa/AppData/Roaming/.minecraft/saves/interpo/")]
        public string outputPath {
            get {
                return ((string)(this["outputPath"]));
            }
            set {
                this["outputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:/DwarfFortress/df_34_11_win/world_graphic-bm-region1-250-16014.bmp")]
        public string biomeMapPath {
            get {
                return ((string)(this["biomeMapPath"]));
            }
            set {
                this["biomeMapPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SpikeTest")]
        public string levelName {
            get {
                return ((string)(this["levelName"]));
            }
            set {
                this["levelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int borderNorth {
            get {
                return ((int)(this["borderNorth"]));
            }
            set {
                this["borderNorth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int borderWest {
            get {
                return ((int)(this["borderWest"]));
            }
            set {
                this["borderWest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204")]
        public int borderEast {
            get {
                return ((int)(this["borderEast"]));
            }
            set {
                this["borderEast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204")]
        public int borderSouth {
            get {
                return ((int)(this["borderSouth"]));
            }
            set {
                this["borderSouth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double caveHeight {
            get {
                return ((double)(this["caveHeight"]));
            }
            set {
                this["caveHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double caveScale {
            get {
                return ((double)(this["caveScale"]));
            }
            set {
                this["caveScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int cavePercentage {
            get {
                return ((int)(this["cavePercentage"]));
            }
            set {
                this["cavePercentage"] = value;
            }
        }
    }
}
